spring:
  application:
    name: account-limit


eureka:
  instance:
    #主机名，不配置的时候将根据操作系统的主机名来获取
    hostname: account-limit
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    #是否将自己注册到注册中心，默认为 true
    register-with-eureka: true
    #是否从注册中心获取服务注册信息，默认为 true
    fetch-registry: true
    serviceUrl:
      # 设置服务注册中心地址
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/