server:
  port: 8080

spring:
  application:
    name: service-consumer

eureka:
  instance:
    #主机名，不配置的时候将根据操作系统的主机名来获取
    hostname: service-consumer
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    #是否将自己注册到注册中心，默认为 true
    register-with-eureka: false
    # 默认从注册中心拉取注册信息的间隔 默认 30秒
    registry-fetch-interval-seconds: 10
    serviceUrl:
      # 设置服务注册中心地址
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/

# 负载均衡策略
#service-provider 为调用的服务的名称
account-limit:
    ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule